# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"

# Install scripts. (runs after repo cloning)
install:
  - cd workspace/assets
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - npm install -g grunt-cli

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - grunt ci

# Don't actually build.
build: off
